---
version: '3.5'
services:
  db:
    container_name: anderson_db
    image: mariadb
    volumes:
      - ./.data:/var/lib/mysql
      - ./brendan.sql:/docker-entrypoint-initdb.d/brendan.sql
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    command: --max-allowed-packet=128M --transaction-isolation=READ-COMMITTED
    networks:
      - database
  drupal:
    container_name: anderson_web
    image: bander2/anderson-intranet
    build: .
    volumes:
      - ./drupal:/var/www/drupal
    ports:
      - 8888:80
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306
      DRUPAL_ENV: dev
    networks:
      - database
networks:
  database:
